<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="LinguaBroAuth._Default" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <script src="Scripts/parse-srt.js"></script>
    <script src="Scripts/SubtitilesWork.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="Scripts/LinguaHub.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <link href="Content/video-js.css" rel="stylesheet" />


    <div class="row" style="position: relative;margin-top: 20px;margin-left: 0px;">
        <video width="640"  class="video-js" controls preload="auto"  data-setup="{}">
            <source src="https://linguabro.blob.core.windows.net/test/The%20Raven.2010.HDRip-AVC%20(720).mp4" type="video/mp4">
            Your browser does not support the video tag.
        </video>
        <div id="subs">
        </div>
    </div>
      <script src="http://vjs.zencdn.net/6.2.7/video.js"></script>
</asp:Content>
