<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Mobile.Master" AutoEventWireup="true" CodeBehind="MobileSubs.aspx.cs" Inherits="LinguaBroAuth.MobileSubs" %>

<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <script src="Scripts/jquery-1.10.2.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="Scripts/parse-srt.js"></script>
    <script src="Scripts/SubtitilesWork.js"></script>
     <script src="Scripts/LinguaHub.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <script type="text/javascript">
        
    </script>

    <style>
        :root {
            --width: 100vw;
            --height: 100vh;
            --max-height: 100%;
            --chrome: 22.5px;
            --outer-border-radius: 25px;
            --thumb-radius: 0px;
        }

        html {
            box-sizing: border-box;
        }

        * {
            box-sizing: inherit;
        }

        body {
            min-height: 100vh;
            display: flex;
            align-items: center;
            background: black;/*radial-gradient(turquoise, midnightblue);*/
            font-weight: lighter;
            font-size: 15px;
            margin:0px;
        }

        .outer {
            position: relative;
            margin: 0 auto;
            width: var(--width);
            height: var(--height);
            border-radius: var(--outer-border-radius);
            border: solid 0px buttonface;
            display: flex;
            align-items: center;
        }

        .inner {
            background: white;
            /*   position: absolute; */
            margin: 0 auto;
            width: calc(100% - var(--chrome));
            height: calc(100% - var(--chrome));
            border-radius: calc(var(--chrome) - 10px);
            overflow-y: scroll;
            overflow-x: hidden;
        }

        .notch {
            position: absolute;
            background: orange;
            width: 3%;
            max-width: 20px;
            height: 50%;
            top: 30%;
            left: calc(var(--chrome)/2);
            border-radius: 0 10px 10px 0;
        }

        ul {
            padding-left: calc(var(--chrome)/4);
            padding-right: 10px;
            margin: 5px 0;
            overflow: hidden;
        }

        li {
            list-style: none;
            padding: 5px 5px;
            border-bottom: 1px solid #dadada;
            transform-origin: center left;
        }

        *::-webkit-scrollbar {
            width: 5px;
            padding: 100px;
            transform: scalex(10);
        }

        *::-webkit-scrollbar-thumb {
            border-radius: var(--thumb-radius);
            background-color: #5555;
            padding-right: 5px;
            transform: scalex(10);
        }
        .selected {
            font-weight:bold;
        }

        
#subsList  a{
    color: black;
    text-decoration: none;
    cursor: pointer;
}

#subsList a:hover {
}
    </style>

    <div class="outer">
        <div class="inner">
            <ul id="subsList">
            </ul>
            <div class="notch"></div>
        </div>
    </div>


</asp:Content>
